#####
# INFISICAL K8 DEFAULT VALUES FIL
# PLEASE REPLACE VALUES/EDIT AS REQUIRED 
#####

namespace: infisical

frontend:
  replicaCount: 1
  image:
    repository: 
    pullPolicy: IfNotPresent
    tag: "latest"

backend:
  replicaCount: 1
  image:
    repository: 
    pullPolicy: IfNotPresent
    tag: "latest"

ingress:
  enabled: true
  annotations: {}
  hostName: example.com
  frontend: 
    path: /
    pathType: Prefix
  backend:
    path: /api
    pathType: Prefix
  tls: []

## Complete Ingress example 
# ingress:
#   enabled: true
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/issuer: letsencrypt-nginx
#   hostName: k8.infisical.com
#   frontend: 
#     path: /
#     pathType: Prefix
#   backend:
#     path: /api
#     pathType: Prefix
#   tls:
#     - secretName: letsencrypt-nginx
#       hosts:
#         - k8.infisical.com

###
### YOU MUST FILL IN ALL SECRETS BELOW
### 
backendEnvironmentVariables:
  # Required keys for platform encryption/decryption ops. Replace with nacl sk keys
  PRIVATE_KEY: MUST_REPLACE
  PUBLIC_KEY: MUST_REPLACE
  ENCRYPTION_KEY: MUST_REPLACE

  # JWT
  # Required secrets to sign JWT tokens
  JWT_SIGNUP_SECRET: MUST_REPLACE
  JWT_REFRESH_SECRET: MUST_REPLACE
  JWT_AUTH_SECRET: MUST_REPLACE

  # Mail/SMTP
  # Required to send emails
  SMTP_HOST: MUST_REPLACE 
  SMTP_NAME: MUST_REPLACE
  SMTP_USERNAME: MUST_REPLACE
  SMTP_PASSWORD: MUST_REPLACE

  # You may replace with Mongo Cloud URI
  MONGO_URL: mongodb://root:root@mongodb-service:27017/

# frontendEnvironmentVariables:
#   INFISICAL_TELEMETRY_ENABLED: true
    