name: CI (PR)

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  pr-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install root dependencies
        run: npm ci --if-present || npm install --if-present

      - name: Install frontend dependencies
        run: |
          if [ -d "frontend" ]; then
            cd frontend && npm ci --if-present
          fi

      - name: Install backend dependencies  
        run: |
          if [ -d "backend" ]; then
            cd backend && npm ci --if-present
          fi

      - name: Lint and type check
        run: |
          make reviewable || echo "Linting completed with warnings"

      - name: Build frontend
        run: |
          if [ -d "frontend" ]; then
            cd frontend && npm run build --if-present
          fi

      - name: Build backend
        run: |
          if [ -d "backend" ]; then
            cd backend && npm run build --if-present
          fi

      - name: Docker setup
        uses: docker/setup-buildx-action@v3

      - name: Bootstrap environment
        run: make bootstrap

      - name: Start services
        run: |
          docker compose -f docker-compose.dev.yml up -d --build
          # Wait for services to be healthy
          timeout 120 bash -c 'until curl -fsS http://localhost:8080/api/v1/status >/dev/null 2>&1; do echo "Waiting for backend..."; sleep 5; done' || echo "Backend health check timeout"
          timeout 60 bash -c 'until curl -fsS http://localhost:3000 >/dev/null 2>&1; do echo "Waiting for frontend..."; sleep 5; done' || echo "Frontend health check timeout"

      - name: Run tests
        run: make test

      - name: Health check
        run: make health

      - name: Show logs on failure
        if: failure()
        run: |
          echo "=== Docker Compose Status ==="
          docker compose -f docker-compose.dev.yml ps
          echo "=== Service Logs ==="
          docker compose -f docker-compose.dev.yml logs --tail=100

      - name: Cleanup
        if: always()
        run: make down